

Comandos do Azure que fiz:

enzo [ ~/azuredev-00e7/DevOps-Aulas ]$ az --version
azure-cli                         2.84.0 *

core                              2.84.0 *
telemetry                          1.1.0

Extensions:
ml                                2.41.1
ssh                                2.0.6

Dependencies:
msal                            1.35.0b1
azure-mgmt-resource               24.0.0

Python location '/usr/bin/python3.12'
Config directory '/home/enzo/.azure'
Extensions directory '/home/enzo/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.12/site-packages/azure-cli-extensions'

Python (Linux) 3.12.9 (main, Mar  4 2026, 02:40:54) [GCC 13.2.0]





enzo [ ~/azuredev-00e7/DevOps-Aulas ]$ az account list
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "11dbbfe2-89b8-4549-be10-cec364e59551",
    "id": "213b06ed-e7f7-4f7b-a22d-f0f15daa85ff",
    "isDefault": true,
    "managedByTenants": [],
    "name": "2tdspg-rm566422-LucasBarrosGouveia",
    "state": "Enabled",
    "tenantId": "11dbbfe2-89b8-4549-be10-cec364e59551",
    "user": {
      "cloudShellID": true,
      "name": "RM561432@fiap.com.br",
      "type": "user"
    }
  },
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "11dbbfe2-89b8-4549-be10-cec364e59551",
    "id": "01bd2f0c-367c-4533-bf77-c3454ada4a18",
    "isDefault": false,
    "managedByTenants": [],
    "name": "2TDSPG-2026-RM561432-ENZO-OKUIZUMI",
    "state": "Enabled",
    "tenantId": "11dbbfe2-89b8-4549-be10-cec364e59551",
    "user": {
      "cloudShellID": true,
      "name": "RM561432@fiap.com.br",
      "type": "user"
    }
  },
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "11dbbfe2-89b8-4549-be10-cec364e59551",
    "id": "39ffaa05-1ee0-46d8-bb89-cdabbdba4288",
    "isDefault": false,
    "managedByTenants": [],
    "name": "2tdspg-rm564836-MiltonMarcelino",
    "state": "Enabled",
    "tenantId": "11dbbfe2-89b8-4549-be10-cec364e59551",
    "user": {
      "cloudShellID": true,
      "name": "RM561432@fiap.com.br",
      "type": "user"
    }
  }
]





enzo [ ~/azuredev-00e7/DevOps-Aulas ]$ az account list / show / list-locations
unrecognized arguments: / show / list-locations

Examples from AI knowledge base:
az account list
Get a list of subscriptions for the logged in account. (autogenerated)

az account list-locations
List supported regions for the current subscription. (autogenerated)

az account list --all
Get a list of subscriptions for the logged in account. (autogenerated)




enzo [ ~/azuredev-00e7/DevOps-Aulas ]$ az group show
the following arguments are required: --name/-n/--resource-group/-g

Examples from AI knowledge base:
az group show --resource-group myresourcegroup
Gets a resource group. (autogenerated)

az account show
Get the details of a subscription. (autogenerated)

az group list --query "[?location=='westus']"
List all resource groups located in the West US region.



enzo [ ~/azuredev-00e7/DevOps-Aulas ]$ az account list -o table
Name                                CloudName    SubscriptionId                        TenantId                              State    IsDefault
----------------------------------  -----------  ------------------------------------  ------------------------------------  -------  -----------
2TDSPG-2026-RM561432-ENZO-OKUIZUMI  AzureCloud   01bd2f0c-367c-4533-bf77-c3454ada4a18  11dbbfe2-89b8-4549-be10-cec364e59551  Enabled  False



enzo [ ~/azuredev-00e7/DevOps-Aulas ]$ az account set --subscription 01bd2f0c-367c-4533-bf77-c3454ada4a18







enzo [ ~/azuredev-00e7/DevOps-Aulas ]$ az vm list
[
  {
    "etag": "\"45\"",
    "hardwareProfile": {
      "vmSize": "Standard_B2ts_v2"
    },
    "id": "/subscriptions/01bd2f0c-367c-4533-bf77-c3454ada4a18/resourceGroups/VM-DEVOPS-LINUX-RM561432_GROUP/providers/Microsoft.Compute/virtualMachines/vm-devops-linux-rm561432",
    "location": "canadacentral",
    "name": "vm-devops-linux-rm561432",
    "networkProfile": {
      "networkInterfaces": [
        {
          "deleteOption": "Detach",
          "id": "/subscriptions/01bd2f0c-367c-4533-bf77-c3454ada4a18/resourceGroups/vm-devops-linux-rm561432_group/providers/Microsoft.Network/networkInterfaces/vm-devops-linux-rm561432896",
          "primary": true,
          "resourceGroup": "vm-devops-linux-rm561432_group"
        },
        {
          "id": "/subscriptions/01bd2f0c-367c-4533-bf77-c3454ada4a18/resourceGroups/vm-devops-linux-rm561432_group/providers/Microsoft.Network/networkInterfaces/vnet_rm561432",
          "primary": false,
          "resourceGroup": "vm-devops-linux-rm561432_group"
        }
      ]
    },
    "osProfile": {
      "adminUsername": "Enzo",
      "allowExtensionOperations": true,
      "computerName": "vm-devops-linux-rm561432",
      "linuxConfiguration": {
        "disablePasswordAuthentication": false,
        "patchSettings": {
          "assessmentMode": "ImageDefault",
          "patchMode": "ImageDefault"
        },
        "provisionVMAgent": true
      },
      "requireGuestProvisionSignal": true,
      "secrets": []
    },
    "provisioningState": "Succeeded",
    "resourceGroup": "VM-DEVOPS-LINUX-RM561432_GROUP",
    "storageProfile": {
      "dataDisks": [],
      "diskControllerType": "SCSI",
      "imageReference": {
        "exactVersion": "22.04.202512181",
        "offer": "ubuntu-22_04-lts",
        "publisher": "canonical",
        "sku": "server",
        "version": "latest"
      },
      "osDisk": {
        "caching": "ReadWrite",
        "createOption": "FromImage",
        "deleteOption": "Delete",
        "diskSizeGB": 64,
        "managedDisk": {
          "id": "/subscriptions/01bd2f0c-367c-4533-bf77-c3454ada4a18/resourceGroups/VM-DEVOPS-LINUX-RM561432_GROUP/providers/Microsoft.Compute/disks/vm-devops-linux-rm561432_disk1_53529578b4b1415db4f0f5cd07f42089",
          "resourceGroup": "VM-DEVOPS-LINUX-RM561432_GROUP",
          "storageAccountType": "Premium_LRS"
        },
        "name": "vm-devops-linux-rm561432_disk1_53529578b4b1415db4f0f5cd07f42089",
        "osType": "Linux"
      }
    },
    "tags": {
      "devops": "pc-devops"
    },
    "timeCreated": "2026-03-24T11:12:06.67791+00:00",
    "type": "Microsoft.Compute/virtualMachines",
    "vmId": "688e969f-4d7d-4346-91ee-b1398986d4c9"
  }
]